### ISSUE TITLE
Set up Apple Watch App with the existing time app

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#11]
Now that we have a very minimal MVP on iOS, I'd like to setup the basic structure for apple watch. 

- [x] create Apple Watch related files
- [x] Connect it to the iOS app so that when the user opens the apple Watch app we can fetch information from core data 
  - I'll need to research this to see what is possible in terms of transferring data.

I'm estimating around 1 Day to do this.

**Comment by sohilpandya** [comment]
We've create the Apple watch instance for the time app. Next step is to connect it to the iOS app using Watch Connectivity. Oh the memory is flowing back. 😄  https://github.com/dwyl/learn-apple-watch-development/issues/17

**Comment by sohilpandya** [comment]
Little update:

- Managed to get the apple watch app running
- also added a table view with a list of fake projects 
![screen shot 2017-03-20 at 17 16 08](https://cloud.githubusercontent.com/assets/2305591/24112293/fbc7fd9e-0d90-11e7-9092-fc3eff964dff.png)

Spent some time setting up the session to connect the iPhone and Apple Watch up, but not having much luck.... so going to stop and will start afresh tomorrow.

**Comment by sohilpandya** [comment]
@nelsonic @iteles I think it might be better to do a stand up tomorrow and skip today's as I've not made the progress that I would've liked. 😢

**Comment by nelsonic** [comment]
@sohilpandya no worries. we all got caught up in client work today. 
Looking forward to tomorrow's progress. ;-) 👍 

On the bright side, your work area is ready for you tomorrow:
![img_4642](https://cloud.githubusercontent.com/assets/194400/24124682/d7a2459c-0dbc-11e7-9441-4efa60ee0971.JPG)

**Comment by sohilpandya** [comment]
**Update from yesterday**

As I mentioned to @iteles I spend a day trying to solve a bug that never existed. 

**What?**
When a user clicked a button on the apple watch, It would send a request to the iPhone (using watchconnectivity), the request was being caught by the debugger on Apple Watch, but not on the iOS app. This has led me to write a very brief intro to debugging in Xcode.

**How to use the Xcode debugger?**

**Breakpoints**
You're very likely to have come across breakpoints before, **it is a point in time where you would like the code to pause execution temporarily**. The main benefit is that it helps you go through the code line at a time when you are trying to debug an issue and most importantly it means that you don't have to litter your code with print statements. 😆 

You can set a breakpoint just by selecting the line number in Xcode and it'll create a breakpoint. 
![screen shot 2017-03-22 at 12 16 15](https://cloud.githubusercontent.com/assets/2305591/24197399/63ea118c-0ef9-11e7-866e-40a4e1415744.png)
As you can see in the image above we've created two variables in our viewDidLoad function and set a breakpoint on the second variable. 

If we run our app now 
![screen shot 2017-03-22 at 12 10 12](https://cloud.githubusercontent.com/assets/2305591/24197478/b0ec1020-0ef9-11e7-856b-7dad84b33c8c.png)
we'll see that the app loads and as soon as it reaches the second variable it will pause the flow of execution. 

And all the executed variables will be available for us to inspect in the Debug area.
![screen shot 2017-03-22 at 12 21 01](https://cloud.githubusercontent.com/assets/2305591/24197571/0bae9f5a-0efa-11e7-940c-a93e9972abe7.png)

You can view that `testingBreakpoint` has been executed and hence we can see it's description, but `breakpointTwo` has not executed and hence doesn't have a description. 

This is a great way to ease into using the debugging tools provided by Xcode, I suggest that you use a breakpoint instead of printing a statement in the console next time you are trying to debug an issue.

**Comment by sohilpandya** [comment]
**Time Estimate**

Estimated 1 Day to complete this task, It's taken me 1 day and 2 Hours to get to the stage where we are able to send a message from the apple watch to the iPhone manually. so not a great start but my next step here is to send the correct information back to the apple watch. Once that is done I can think of automating that service rather than asking the user to manually fetch it.

**Comment by sohilpandya** [comment]
**update**

**The process for sending a message from the Apple Watch to the iPhone which then returns back some information to the Apple watch as a callback**

### Watch 
When the user selected `fetch info` we were running the `sendMessage` method from watchConnectivity to send a message to the iPhone
![screen shot 2017-03-22 at 15 29 58](https://cloud.githubusercontent.com/assets/2305591/24205839/6f204740-0f14-11e7-8765-95c2b6ac0491.png)
it takes 3 arguments:
- the message you want to send to the phone
- callback handler which will wait for the message that you reply back with from the iphone
- error handler where you can decide what to do in case of an error. 

### Phone
On the Phone, we are waiting for a message to be heard and we are doing so by using the method `didReceiveMessage` 
![screen shot 2017-03-22 at 15 32 59](https://cloud.githubusercontent.com/assets/2305591/24206036/ff66061e-0f14-11e7-8dbd-311fe2f22cc1.png)
We are then checking if the message is what we expected and then responding back to the replyHandler with some data. (in the screenshot we are sending back the store as well as the list of unique projects)

**The Process to automate the ability to view list of tasks without having to click a button on the Apple Watch**

On the Apple Watch we have a method called `activationDidComplete` which will run once the session has been established. All we need to do is move the logic from the button to this method 
![screen shot 2017-03-22 at 15 37 59](https://cloud.githubusercontent.com/assets/2305591/24206246/8d1d2ec4-0f15-11e7-8fe4-168509ab8b8e.png)

And now when we rebuild, we'll be able to fetch information on connection! You are free to do what you like with the newly received information. For our case we've updated the tableView on the Apple Watch with the latest information.

🎉

**Comment by sohilpandya** [comment]
I'm very pleased with the progress that was made today! 😊 

- [x] managed to get the data synced across when the user first starts the app. 
- [x] managed to update the data onto the watch if a user adds or deletes a project from the phone. This instantly updates the data on the watch too! 

Total Time spent on this has been **2 Days** although we are doing a little more than just fetching the information from the phone. we are also updating the information on the watch if there has been an addition on the phone.
