### ISSUE TITLE
Apple Watch Notification when timer hits 25mins

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#14]
When the user starts a timer, there may be times when they forget that they have started a timer, We want to notify the user with an alert when they reach 25mins.

In the future we can give them two options:
- Take a break: which will stop the timer and save the time in the database
- Continue: which will just continue

**Comment by iteles** [comment]
A couple of future extensions:
+ Switch this functionality on and off (I won't be thrilled to continuously be buzzed every 25 mins if I'm not using pomodoros)
+ Change the time interval

**Comment by sohilpandya** [comment]
I have implemented the haptic feedback and alert, but they only appear when the app is active when the app is inactive/running in background It is unable to send this off to the watch. 

The alternative is Notifications, which will take quite a bit longer to implement, and we might want to spend time elsewhere.
