### ISSUE TITLE
Apple Organisation Developer Account

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#16]
After having a look at the options for registering as a developer, I think the best way to do this would be to register dwyl as an organisation and get a developer account for dwyl. (costs $99/year)

![screen shot 2017-03-29 at 18 51 38](https://cloud.githubusercontent.com/assets/2305591/24468679/f76b6098-14b0-11e7-96b4-17ac9e5c6a18.png)

We do need a DUNS Number, @markwilliamfirth do we have this or can we obtain this with ease? 

If it's a pain to get a hold of then option two is to create an individual account under a dwyl email address. 

Either way, we need to setup an apple account. If you are happy then I can create an account under 
finance+ios@dwyl.io, that way we can setup the forwarding to my email address. 

How does this all sound? 😄

**Comment by ghost** [comment]
@sohilpandya  I've sent you an email with the DUNS number in case you need it

**Comment by sohilpandya** [comment]
Thanks for that @markwilliamfirth I'll be tackling this on Monday. 😄

**Comment by sohilpandya** [comment]
I'm going to set up a new apple id for use with the dev account for the email finance+ios@dwyl.io. Attaching some of the information that is required. 
![screen shot 2017-04-03 at 10 16 53](https://cloud.githubusercontent.com/assets/2305591/24602940/d6044a60-1856-11e7-9a2b-b6868e70c1fc.png)

What should the name and birthday be for the account? @markwilliamfirth

**Comment by sohilpandya** [comment]
I've registered for an organisation account for Apple and now waiting to hear back from them. 

![screen shot 2017-04-20 at 12 16 43](https://cloud.githubusercontent.com/assets/2305591/25228170/4c291a3a-25c3-11e7-8951-21720e5f34b9.png)

**Comment by sohilpandya** [comment]
@nelsonic Apparently they tried to contact the number on the site to confirm the details but didn't manage to get through to you. 

I've forwarded an email that they sent to us, it'll be great if you could verify us so that we can get our account and I can make a start on the TestFlight stuff. 👍

**Comment by ghost** [comment]
fyi office number is 020 3302 4210

**Comment by sohilpandya** [comment]
@nelsonic @iteles any update on this one? 

@markwilliamfirth thanks for the number, but I think they need to speak to one of the founders in order to authorize the account. 🤔

**Comment by sohilpandya** [comment]
Thanks @iteles 🎉

**Comment by iteles** [comment]
Let me know if you need me to do anything else. 👍

**Comment by sohilpandya** [comment]
We now have a dev account with Apple! 🎉
