### ISSUE TITLE
UI Changes for iPhone App

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#18]
As discussed yesterday, we need to make a few changes to the UI of the app to make it look slightly more appealing.

- [x] Automatic Colours for Projects ( Pick a set of colours and then assign to a given project)
- [x] Colour for individual tasks. 
- [x] Potentially storing more data about individual tasks? (time when it was completed)
- [x] App logo

**Comment by sohilpandya** [comment]
I'd like to spend a couple of day's trying to polish certain things off including the items above. 

Estimated time **2 Days**

**Comment by sohilpandya** [comment]
Automatic colors:
- [x] update the database so that it can hold a UIColor (Store as a type transformable in core data)

**Comment by sohilpandya** [comment]
**update** we now have a random color generation that happens when the user saves a new project. Next task is to send this over to the watch and have it represented for each of the projects. 

<img width="466" alt="screen shot 2017-04-18 at 14 39 25" src="https://cloud.githubusercontent.com/assets/2305591/25133602/0af33534-2445-11e7-8ebe-a433ea223d86.png">

**Comment by iteles** [comment]
@sohilpandya Did @harrygfox Send you his designs?

**Comment by sohilpandya** [comment]
@iteles not yet.

**Comment by sohilpandya** [comment]
I've managed to get the random colors to work, but because the data store contains a UIColor object, it is causing an error when sending it to the Apple Watch. So need to slightly change the structure of the store again so that we can pass the data to the apple watch again.

**Comment by sohilpandya** [comment]
The above changes have been implemented and released a while ago.
