### ISSUE TITLE
dwyl original logo file

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#38]
Hi @markwilliamfirth,

could you please link me to the original logo file so that I can make some changes for the apple watch logo as it currently doesn't fit the circular app icon.
<img width="469" alt="screen shot 2017-04-24 at 17 57 39" src="https://cloud.githubusercontent.com/assets/2305591/25428087/a4f0f4be-2a6c-11e7-9a20-379ddde0ef2a.png">

**Comment by ghost** [comment]
@sohilpandya in the dwyl branding folder :)

https://drive.google.com/open?id=0B6RCV_WfdQQyMDlOMWVRekhhWHM

**Comment by sohilpandya** [comment]
Thanks @markwilliamfirth ❤️

**Comment by sohilpandya** [comment]
# iPhone
![phone-logo-v2](https://cloud.githubusercontent.com/assets/2305591/25895607/7e73ebc2-3578-11e7-869d-360dd6cf2dea.png)

# Watch
![watch-logo-v3](https://cloud.githubusercontent.com/assets/2305591/25895608/7e8bbd7e-3578-11e7-961b-c871d2bbd1f0.png)

**Comment by sohilpandya** [comment]
Thanks again for the original files, will close this issue now.
