### ISSUE TITLE
time is taken on the app store

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#42]
Trying to register the app for upload and here is the error we are getting. 
<img width="466" alt="screen shot 2017-04-28 at 19 56 46" src="https://cloud.githubusercontent.com/assets/2305591/25543037/e11b5704-2c4c-11e7-850a-c51debf0c240.png">

@iteles @nelsonic have you thought of another name for the app?

I'm going with `dwyl time` for now. Let me know if we have an alternative.

**Comment by nelsonic** [comment]
is `dwyl` taken in the App Store?

**Comment by sohilpandya** [comment]
It doesn't look like it. I have changed the name of the app to `dwyl` on iTunes Connect.
<img width="734" alt="screen shot 2017-05-04 at 14 10 24" src="https://cloud.githubusercontent.com/assets/2305591/25704969/7cf9a344-30d3-11e7-86ad-d82e1eb18453.png">

**Comment by iteles** [comment]
👍
