### ISSUE TITLE
What should the process for pushing to Testflight be?

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#51]
At this current moment GitHub and iTunes Connect workflow are not in sync. 

Should they be in sync? so that only the information present in the master branch be pushed to iTunes Connect for TestFlight. 

Does that make sense?

**Comment by iteles** [comment]
Does to me. Master is the production version.

**Comment by sohilpandya** [comment]
Thanks for that! 👍
