### ISSUE TITLE
Which Color?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/time-apple-watch-app#56]
@harrygfox in the interest of you helping us to Alpha Test (_and improve!_) the Apple Watch App ... 
***which color*** do you want? https://www.apple.com/uk/apple-watch-series-2

**Comment by harrygfox** [comment]
**Space Black** I think, @nelsonic - is that what you went for?

**Comment by nelsonic** [comment]
@harrygfox yeah, Black Case & Black Strap. same as @JoeTanner `#StealthMode` 😉

**Comment by harrygfox** [comment]
@nelsonic please can I be made a member of this repo so that I might label issues?

**Comment by iteles** [comment]
Done @harrygfox

**Comment by harrygfox** [comment]
Thank you, @iteles !
