### ISSUE TITLE
View a list of existing tasks on the iPhone

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#6]
**As a user I would like to see a list of tasks with the total time spent on each of them on my iPhone**

This involves the user to be able to see a list of existing tasks and the total time spend on each of the tasks. 

- [x] setup Time project in Xcode 
- [x] Create a custom table view
- [x] Nav bar with a DWYL logo in the middle and an Add button on the right.(will come in handy for the next task #7)
- [x] List of dummy tasks with total time 

@iteles @nelsonic will start once I get the go ahead. 👍

**Comment by sohilpandya** [comment]
Currently created the nav-bar and added the dwyl logo, although I am unable to center it. 
<img width="374" alt="screen shot 2017-03-06 at 12 33 04" src="https://cloud.githubusercontent.com/assets/2305591/23610099/27ad18c8-0269-11e7-85ec-b11374ea1b00.png">

Planning to move on as I've spent a bit of time trying to figure out how it works, will return to it at a later stage.

**Comment by sohilpandya** [comment]
We are now able to view a list of tasks with a time attached to each of them. 
<img width="375" alt="screen shot 2017-03-06 at 15 51 31" src="https://cloud.githubusercontent.com/assets/2305591/23617361/cf4d079e-0284-11e7-9a24-d7f948304549.png">


The fakeTaskArray looks like:
```js
[["taskName": "iOS", "taskTime": "00H24M", "red": 155.0, "green": 226.0, "blue": 0.0]]
```

We are also setting a custom background color for each item on the table. (**sorry for the terrible color choices...** 😟)

**Potential issues**: 
I am unsure of how to store the taskTime. ❓

**Comment by nelsonic** [comment]
looking good! 😍

**Comment by sohilpandya** [comment]
Thanks for merging in @nelsonic!

Total Time for this task: 5 Hours. on point with the estimation 😎

**Comment by sohilpandya** [comment]
**When you select a task, it takes you through to the task details view.**
![screen shot 2017-03-14 at 10 08 20](https://cloud.githubusercontent.com/assets/2305591/23895586/2c14eec8-089e-11e7-969a-1f02fce60927.png)

**Comment by sohilpandya** [comment]
Wrong Issue..... 😭
