### ISSUE TITLE
Can't start timer on iPhone 5(SE) in v1.1 (8)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/time-apple-watch-app#61]
Upgraded to version 1.1 (8):
![img_6841](https://cloud.githubusercontent.com/assets/194400/25890765/b29e1dc6-3566-11e7-907c-2633bfb9ac46.PNG)

Opened the app:
![img_6844](https://cloud.githubusercontent.com/assets/194400/25890844/fc523790-3566-11e7-9bb4-29bc17ddd943.PNG)
![img_6845](https://cloud.githubusercontent.com/assets/194400/25890847/fc779a58-3566-11e7-95b1-5cc1fc189c61.PNG)
![img_6846](https://cloud.githubusercontent.com/assets/194400/25890845/fc65f668-3566-11e7-8dad-16c6ef2535ef.PNG)
![img_6847](https://cloud.githubusercontent.com/assets/194400/25890846/fc66f4c8-3566-11e7-87f5-623d423b00b0.PNG)

But when I navigate into the new task, 
there is no UI (button) to _start_ a timer...
![img_6848](https://cloud.githubusercontent.com/assets/194400/25890942/3c61d5d4-3567-11e7-99b1-0a5addb3320e.PNG)

**Comment by sohilpandya** [comment]
I've fixed this particular issue and will push through an updated version in the next build.

**Comment by sohilpandya** [comment]
fixed on 5s screen size.
