### ISSUE TITLE
iPhone time incorrect compared to correct watch timers

### ISSUE THREAD

**Issue by iteles** [dwyl/time-apple-watch-app#64]
**Version:** 1.1 (8)

Steps to recreate bug:
1. Create task 'dwyl admin' on iPhone
2. Start timer on Watch
3. Stop timer on watch
4. Switch back to iPhone app on the iPhone

dwyl watch says correct time:
![img_2500](https://cloud.githubusercontent.com/assets/4185328/25906943/efcdad9c-359d-11e7-8cc9-f4380ebd2b23.JPG)

Apple watch says:
![img_2503](https://cloud.githubusercontent.com/assets/4185328/25906964/f7f53dc8-359d-11e7-8717-d4fc3fad876c.PNG)
![img_2502](https://cloud.githubusercontent.com/assets/4185328/25906968/fba704f6-359d-11e7-9709-a07c9d2273ae.PNG)

**Comment by sohilpandya** [comment]
Thanks for the detailed report, I've replicated this issue on my device too, the problem I'm having is replicating it on the simulator. 

e.g.
**Real Device**
- started the timer on watch -> 30min -> stopped the timer on the watch
- The time is added incorrectly as shown in the screenshots above
- Big time discrepancy

**Simulator**
- started the timer on watch -> 30min -> stopped the timer on the watch
- The time is added correctly on the phone. 
- no time discrepancy

😕 still looking into it.

**Comment by sohilpandya** [comment]
So I am still unable to replicate it when the device is plugged into the laptop. As soon as I remove the connection the issue appears. 😟 

Cue the refactor... 🔧

**Comment by sohilpandya** [comment]
A Couple of things I can do on our end:
- instead of sending the time in seconds from the watch to the phone, I can send the start date and end date.

**Comment by sohilpandya** [comment]
**end of day update**

- Currently I am stuck on a potential memory/notification leak 👎 
- I am subscribing to a notification on each view, but for the project details view I keep on getting resubscribed. So by the end of it I am left with a lot more subscriptions than just one. 
- Plan is to debug and look for solutions. 

**keyword search**
- deinit not getting called
- unable to clear notification observers from a view.

**Comment by sohilpandya** [comment]
created a stackoverflow issue http://stackoverflow.com/questions/43936292/ios-unable-to-remove-notification-observer-deinit-not-getting-called

**Comment by sohilpandya** [comment]
God save **STACKOVERFLOW** http://stackoverflow.com/questions/43936292/ios-unable-to-remove-notification-observer-deinit-not-getting-called
🎉

**Comment by sohilpandya** [comment]
Would like to get feedback on this, I did push a fix at the end of Friday, would like to hear if that did the trick or not. 👍 @iteles

**Comment by iteles** [comment]
@sohilpandya Seems to have done the trick from my testing this week :tada:
