### ISSUE TITLE
Ability to add a Tasks

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#7]
**As a user I would like to add a new task**

Once we have set up the basics in #6 we can move onto providing the users with the ability to add new tasks.

- [x] Add button from nav bar to redirect user to a view where they can add a new task 
- [x] Once the user adds a new task it will appear in the table view in #6 
- [x] Remove an existing task
- [x] Saving task to Core data

Potentially need to figure out the best place to store this data. Potentially do some research around how to save to local phone storage.

**Comment by iteles** [comment]
FYI @sohilpandya A photo of a paper sketch is extremely useful in this kind of situation too 👍 Good for historical reasons!

**Comment by sohilpandya** [comment]
![img_9135](https://cloud.githubusercontent.com/assets/2305591/23700300/4f8913ec-03ea-11e7-9ddd-5891d1acdb04.JPG)
How I plan to tackle this issue 😄

**Comment by sohilpandya** [comment]
Added ability to navigate to and from the new AddTaskView Controller, was stuck on how I would go about dismissing the view, managed to find the related method 😄 
https://developer.apple.com/reference/uikit/uiviewcontroller/1621505-dismiss

**Comment by sohilpandya** [comment]
**Little update**
I've not been able to get the save button to enabled when the text field is filled in.
tried to achieve this by using `textFieldDidEndEditing` method, but this isn't firing 😢 
[Google search](https://www.google.co.uk/search?q=textfielddidendediting+not+called&rlz=1C5CHFA_enGB734GB734&oq=textFieldDidEndEditing&aqs=chrome.2.69i57j0l5.2242j0j7&sourceid=chrome&ie=UTF-8)


**Solved the issue** by resigning the first responder for the text field
```
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        taskName.resignFirstResponder()
        return true
    }
```

**Comment by sohilpandya** [comment]
Halted work for the day, current status:
- unable to save the data 😢

**Comment by sohilpandya** [comment]
**update**

I am putting this task on halt and taking a slight detour, I've had a chance to speak with @nazywamsiepawel about the best way to go about storing the data and he recommends that I look into **core data** rather than `nscoding + nsobject`. 

**Core Data** is how most of the data should be stored for the app and takes its grounding from SQL, so eventually you will be able to form relationships in your database.

**Comment by nazywamsiepawel** [comment]
@sohilpandya after spending some time with core data and understanding the fundamentals you can use one of the wrappers (like https://github.com/carambalabs/SugarRecord) to make development faster.

**Comment by iteles** [comment]
Thank you @nazywamsiepawel !

**Comment by sohilpandya** [comment]
I've updated the todo list on the top to now include the ability to remove tasks as well as the tasks now being stored in core data. 

Time required to build the additional view and flow for adding tasks: 4 Hours 
But the time taken to read up on `core data` and then implement the ability to save/remove tasks from the database took: 1.5 Days. 
The **total is 2 Days** for this task, wildly underestimated if we look at the total of 5 Hours 😞 but did split my time between this task and https://github.com/dwyl/learn-apple-watch-development/issues/28
