### ISSUE TITLE
Watch Time app only show 5 projects/tasks

### ISSUE THREAD

**Issue by iteles** [dwyl/time-apple-watch-app#70]
To recreate this issue:
1. Create 5 tasks.
2. Create the 6th on the phone
3. This does not show up on the Apple Watch and after a few seconds, crashed the iPhone app
4. Create a 7th task on the iPhone app ➡️ Adding new tasks no longer seems to crash the iPhone app and I can track the tasks on the phone but still doesn't show up on the watch

![img_2588](https://cloud.githubusercontent.com/assets/4185328/26164073/74b669c4-3b23-11e7-9e18-25949c06ab16.JPG)
![img_2587](https://cloud.githubusercontent.com/assets/4185328/26164074/74c003bc-3b23-11e7-856e-f39732449cf9.PNG)

**Comment by sohilpandya** [comment]
Hi @iteles,

What are the exact steps for recreating this issue? I've just added a few dummy projects and it's sending it to the watch fine. (added 7 tasks and all showing up fine. 😟)

**Comment by iteles** [comment]
The exact steps I took are the exact steps I put in the original issue.

I'll test this again! The API stuff is more important at the moment anyway :)

**Comment by iteles** [comment]
Figured it out, thanks @sohilpandya ! 

Looks like the watch app is only updated with new tasks if a timer is not running.

This will probably need to be revisited from a UX perspective but closing for now 👍
