### ISSUE TITLE
Complication to show progress on the "main" face of the watch

### ISSUE THREAD

**Issue by nelsonic** [dwyl/time-apple-watch-app#82]
@sohilpandya can you please investigate adding a "complication" to the watch face so that we can see the active task/timer without having to go into an app?
+ [x]  is it possible?
+ [x] can we show a "live timer" (_e.g: number of whole minutes remaining on estimate or time elapsed in minutes?_)
+ [x] does it consume lots of battery?
+ [x] are there size restrictions?

Please/Thanks!

**Comment by sohilpandya** [comment]
I'm planning to spend a half a day to spike this and see what is possible, here is a list of resources I've found so far:

- https://developer.apple.com/library/content/documentation/General/Conceptual/WatchKitProgrammingGuide/ComplicationEssentials.html
- https://developer.apple.com/library/content/documentation/General/Conceptual/WatchKitProgrammingGuide/ManagingComplications.html
- https://developer.apple.com/videos/play/wwdc2015/209/

**here is another article that I found useful, it is in German so thank god for google translate**
- https://www.ralfebert.de/tutorials/watchos-complications/

**Comment by sohilpandya** [comment]
**current progress**
I've been able to work out the very basic usage for complications as you can see in the screenshot below
<img width="139" alt="screen shot 2017-07-05 at 12 40 09" src="https://user-images.githubusercontent.com/2305591/27862939-ae04536c-617f-11e7-9545-a28755e18b23.png">

- I've attached a complication for the following types:
    - modular large
    - modular small

We can add text and images to these sections, some sections have more customisability compared to others. 
**modular large**
we can have a header as well as two column of texts in each of rows. 
**modular small**
we can have some inner text and show progress on the outer ring. (circular ring)


### My next steps are to see if we can display a running timer on the complication. 

Something to note: we cannot interact with the complication, it can only be used to show data, so if a user clicks the complication they'll be taken to the watch app.

**Comment by sohilpandya** [comment]
**Here is the updated result of the spike**

- We **should** be able to show a live timer on the complication.
    - using the class **CLKRelativeDateTextProvider**
- It does not consume extra battery it's a feature that Apple provides in clock kit SDK
- Yes, there are size restrictions, what we need to figure out is what we want to display on the different complications at a couple of different point in time. 
    - When the timer is running we can show the live timer
    - When the timer is not running, what should we show?

The question is how do we display these for the different complications of which there are 7? I would suggest if we do tackle this that we take on just a couple of complications to start with. 
- Modular Small
- Modular Large
 
will outline the solution in a separate issue. But I am hoping that the spike answered the initial questions that we had about complications. (Total Time taken: 6h)

**Comment by sohilpandya** [comment]
Can close this issue as we've added two sets of complications for the app. We are in a position to add it to the rest of the complications. 

As a side note, the small circular complication is really cool in that it can show a ring in ratio to the time, so if in the future we run the timer down instead of up then this complication can be used to fill the ring as the timer comes close to finishing.
