### ISSUE TITLE
Add dwylbot to this repo

### ISSUE THREAD

**Issue by iteles** [dwyl/time-apple-watch-app#88]
As a PO, I would like to see [dwylbot](https://github.com/dwyl/dwylbot#install) added to this issue so that we can ensure we're following process as well as testing out dwylbot!

**Comment by sohilpandya** [comment]
Tried installing and failed on the first step. 😢 
https://github.com/dwyl/dwylbot/issues/131

**Comment by iteles** [comment]
Amended permissions 🙄 Please try again?

**Comment by iteles** [comment]
I've given dwylbot access to this repo. Checking if it's working now.

**Comment by iteles** [comment]
Now we're cooking with gas 👍
