### ISSUE TITLE
Ability to View Task in detail

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/time-apple-watch-app#9]
**As a user I would like to view an existing task so that I can start a new timer for the task and view a history of completed tasks.**

- [x] Create a view Controller for Task Details (T4h)
  - I still need to figure out the best layout to use for this particular controller
  - As you can see in the image below, it needs to have a section for starting the timer alongside having a list view below it.
- [x] Add ability to time a Task (T6h)
  - Create a stopwatch
  - Add a new table in Core Data for saving this information and reference the existing Task table. 
  - Once the user stops the timer, it saves the new data with the total time and the timestamp when it was completed. 
- [x] View list of existing Tasks (T3h)
  - Fetch all the tasks that are completed and then display them below in a chronological order. 

![img_6299](https://cloud.githubusercontent.com/assets/2305591/23851491/a04683ec-07db-11e7-959b-9645f019e20d.JPG)

**Comment by sohilpandya** [comment]
I've been implementing the additional view controller when a user selects a given task. 

At the moment it does redirect to the correct view controller, but the data being sent is one step behind. 

so for e.g. If I select a task called Ines, then I am not getting any data through, but if I go back and select Nelson, then the data coming through is "Ines" which is what I selected before. 🤔  Really strange, will continue to figure out what is wrong, otherwise might try to take a different approach.

**Comment by sohilpandya** [comment]
**Solved the issue related to delay of information being passed to the new viewController**

Issue was that I was passing the information in didSelectRowAt which delayed the information being passed to the new view controller. I'm now sending the data in prepareForSegue and it is working OK. 👍 

![screen shot 2017-03-13 at 12 11 32](https://cloud.githubusercontent.com/assets/2305591/23853907/ae4790ca-07e6-11e7-8018-7476a41c7355.png)

**Comment by sohilpandya** [comment]
**When you select a task, it takes you through to the task details view.**
![screen shot 2017-03-14 at 10 08 20](https://cloud.githubusercontent.com/assets/2305591/23895586/2c14eec8-089e-11e7-969a-1f02fce60927.png)

**Comment by sohilpandya** [comment]
OK, in the process of building the timer and the additional view, I've managed to break the view which adds a new task. 😞 

Will spend some time trying to figure out why the ability to add a task has broken down.

**Comment by sohilpandya** [comment]
**update**

fixed the issue related to navigation not working. Storyboard connections weren't in the right order which caused it to break. 


We now have a fairly simple timer in place with a terrible start/pause/stop icons. My next plan is to store it into the database when a user stops the timer.

**Comment by sohilpandya** [comment]
I've halted work on this particular task, I've gotten as far as:
- start/stop a timer
- created a table where we would like to store this information. 

But, I've not been able to get my head around how the relationship works in core data. I've done quite a bit of research but had no luck trying to figure out how one would implement the saving of data whilst keeping the relationship. 

I am saving the data but the task_id which is the relationship between the two tables comes up with `relationship fault`
![screen shot 2017-03-14 at 16 21 12](https://cloud.githubusercontent.com/assets/2305591/23910693/775cf194-08d2-11e7-963a-fe1c0041431d.png)

![screen shot 2017-03-14 at 16 22 51](https://cloud.githubusercontent.com/assets/2305591/23910704/8079b6f4-08d2-11e7-84ca-1efc0b9c0c06.png)

**Comment by nelsonic** [comment]
@sohilpandya did you take a snap of the simplified (_single-table_) database schema?

**Comment by sohilpandya** [comment]
@nelsonic thanks for taking the time to have a chat with me with regards to the issue that I was having. 

After a little more work on it over the last few hours here is where I stand:
- I no longer get the error above, instead I am able to set the correct relationship when creating a task
<img width="441" alt="screen shot 2017-03-15 at 00 34 39" src="https://cloud.githubusercontent.com/assets/2305591/23928358/31a53c66-0917-11e7-8477-879a8e5747ed.png">

<img width="711" alt="screen shot 2017-03-15 at 00 33 36" src="https://cloud.githubusercontent.com/assets/2305591/23928348/2a40ba0e-0917-11e7-969e-2c3b9ada187b.png">

- This now means that when a user selects a project, I am able to do a search query which will return only the tasks that belong to the given project. (currently logging it in the console as seen in screenshot below) 
```js
NSPredicate(format: "project_name.name = %@", name) 
// search task table and return only the tasks that have a project_name.name of "xxx"
```
<img width="661" alt="screen shot 2017-03-15 at 00 37 40" src="https://cloud.githubusercontent.com/assets/2305591/23928453/bfe10442-0917-11e7-813d-f72c16c4601c.png">



- Now this leaves us with the question of whether I should continue using this layout for the data or use a simpler structure that we discussed earlier today:
![img_1595](https://cloud.githubusercontent.com/assets/2305591/23928504/0395f8a0-0918-11e7-82e3-cc35c571b369.JPG)


What are your thoughts? multiple table route or the single table route?

**Comment by nelsonic** [comment]
@sohilpandya I don't have a preference for data structure on the _Device/Native App_.
The ultimate objective of the Native/Watch App will be to _communicate_ with the Server where we can collect tasks and time-taken. That data will be stored in PostgreSQL in a ["Denormalised"](https://en.wikipedia.org/wiki/Denormalization) form i.e. "single table" (_for task/time records_) because ***join queries*** to render simple views **are _slow_** (_at scale_). 
> Once I've had a chance to write: https://github.com/dwyl/learn-kappa-architecture we can simplify our data on the _server_...

**Comment by sohilpandya** [comment]
In that case, I can scale this back and go with the layout that we came up with in the evening. As much as I'd like to get slightly more stuck into Core Data, I think it can be a bit of a rabbit hole. (Did you see me yesterday 😟)

I'll branch off, clean the data up and follow the structure we talked about yesterday.

**Comment by nelsonic** [comment]
@sohilpandya yeah, "core data" is something to explore further at a later stage, 
right now you know what you need to ship. 😉

**Comment by sohilpandya** [comment]
Latest structure for the data
<img width="169" alt="screen shot 2017-03-15 at 11 03 51" src="https://cloud.githubusercontent.com/assets/2305591/23945642/2e6d675a-096f-11e7-8117-31216f2966ee.png">

Onto refactoring the code so that it works with the new layout of the core data.

**Comment by sohilpandya** [comment]
**update**

After refactoring to the single table for core data, I have also fetched all the tasks that have taken place for a given project. 
- [x] added custom table view for each task **apologies for the garish colours again! 😆 **

![screen shot 2017-03-15 at 12 56 41](https://cloud.githubusercontent.com/assets/2305591/23949412/fd5f3336-097e-11e7-9c24-7fe05aa9447b.png)


The issue in the above screen is that it lists all the items including the first instnace of creating the project which will have no time. So I need to create a query to only fetch data where the total_task_time != 0

I also have a similar issue on the home screen of the app:
![screen shot 2017-03-15 at 13 00 48](https://cloud.githubusercontent.com/assets/2305591/23949526/6ffe95da-097f-11e7-9e4d-fc01e53e7406.png)

It is currently fetching all the information, I need to narrow the query to only return unique project_name back.

**Comment by sohilpandya** [comment]
Having paired with @nelsonic for a pomodorro here is the structure we would like to get once we fetch all the information from the db. 

```js
// create a store which holds individual projects
var object = [String: Dictionary<String, Any>]()

// once we gather the information for each project we can assign it in the following manner
object["ios"] = [ "project_name": "iOS", "total_time": 64, "red": 122.2, "blue": 123.2, "green": 12.2]
object["dwyl"] =  [ "project_name": "dwly", "total_time": 1123, "red": 12.2, "blue": 123.2, "green": 2.2]
object["sohil"] =  [ "project_name": "sohil", "total_time": 12264, "red": 222.2, "blue": 13.2, "green": 152.2]

for item in object {
    print("\(item.key)") // prints "ios", "dwyl", "sohil"
    print("\(item.value["total_time"]!)") // prints 64, 1123, 12264
}
```

**Comment by sohilpandya** [comment]
We are now ordering data in the order found above. The home view does not have any duplicates and has the total time:
![screen shot 2017-03-16 at 12 42 05](https://cloud.githubusercontent.com/assets/2305591/23996653/1d477fb0-0a46-11e7-9802-d911e75ded55.png)

**Comment by sohilpandya** [comment]
I feel we've finally managed to get to the end of this issue. 

Today I've completed the following:
- [x] managed to create a store for the homepage, which only shows a list of unique projects with the total time and related colours
- [x] Updated the Project detail view so that it only shows tasks which have a time linked to it. 
- [x] When the timer is stopped, it automatically adds the new time to the table and updates the home page view with the total time. 

Alongside these tasks, I spent a lot of time changing the codebase to make it work. I wouldn't call it refactoring, although there are parts of the code which look a lot nicer now :) I also spent some time researching what the best way to store the timer information is, using Date object or Calendar object, but still unsure about the best approach. You can see that from the table below
![screen shot 2017-03-16 at 19 13 52](https://cloud.githubusercontent.com/assets/2305591/24014424/cd5b41d0-0a7c-11e7-9609-43821cb9408c.png)


I estimated a total of 1.5 days but it has taken me **3.5 days**. I would've cut out at least a whole day if not slightly more if I hadn't gone down the route of implementing multiple tables with relationships in Core Data. 

@nelsonic was really helpful 🌟  twice this week in terms of steering me in the right direction when I was driving down a hole 😟 
1. when he suggested that I go down the route of single table in core data and 
2. when he suggested that I create a store object instead of faffing about with trying to figure out complicated NSPredicate queries which may or may not exist on the internet. 


I have two things I can try to tackle next and I'd like your opinion as to which one I should do first. 
- At the moment, if a user goes out of the project detailed view screen, then the timer becomes obsolete if you leave that view, if they had started a timer it would not remember that when you come back to the same project detail view. I can make this my next task or
- start on building the apple watch app. ( I think I should start this one, the one above can be taken care of at a later date. Do you guys agree? @nelsonic @iteles)
